This is to find the exact directory of the code, this may take a while btw

In [1]:
import os

for Root, Dirs, Files in os.walk("/kaggle/input"):
    Level = Root.replace("/kaggle/input", "").count(os.sep)

    if Level < 2:
        print(Root)
        for File in Files[:10]:
            print("   ", File)

/kaggle/input
/kaggle/input/competitions

KeyboardInterrupt:

In [10]:
!ls /kaggle/input/competitions/rsna-knee-abnormality-detection

sample_submission.csv  test_series	train.csv     train_series.csv
test.csv	       test_series.csv	train_series

# Load the CSVs

In [11]:
import pandas as pd

DataRoot = "/kaggle/input/competitions/rsna-knee-abnormality-detection"

Train = pd.read_csv(f"{DataRoot}/train.csv")
TrainSeries = pd.read_csv(f"{DataRoot}/train_series.csv")

print("Train:", Train.shape)
print("Train Series:", TrainSeries.shape)

display(Train.head())
display(TrainSeries.head())

Train: (4407, 14)
Train Series: (24371, 5)

,StudyInstanceUID,Report,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
0,1.2.826.0.1.3680043.8.498.10004873229099053869...,Técnica: RMN de la rodilla. Resultados: Rotura...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.2.826.0.1.3680043.8.498.10004945927472656027...,[DATE]: * MR Knie Rechts 15ch AA Klinische Inl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.2.826.0.1.3680043.8.498.10009278692606631573...,Hallazgos:\nNo hay alteraciones en significati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.2.826.0.1.3680043.8.498.10009639203170750274...,"In the medial compartment, the meniscus is no...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.2.826.0.1.3680043.8.498.10013663742400736029...,CONSTATATIONS :\n\nFractures :\nAucune.\n\nAli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,StudyInstanceUID,SeriesInstanceUID,Fluid_Sensitive,Fat_Suppression,Anatomical_Plane
0,1.2.826.0.1.3680043.8.498.10004873229099053869...,1.2.826.0.1.3680043.8.498.12343110195036213483...,1,1,Sagittal
1,1.2.826.0.1.3680043.8.498.10004873229099053869...,1.2.826.0.1.3680043.8.498.13821229744997220641...,1,1,Axial
2,1.2.826.0.1.3680043.8.498.10004873229099053869...,1.2.826.0.1.3680043.8.498.23084836536722595275...,0,0,Coronal
3,1.2.826.0.1.3680043.8.498.10004873229099053869...,1.2.826.0.1.3680043.8.498.40734206102458723096...,1,1,Coronal
4,1.2.826.0.1.3680043.8.498.10004873229099053869...,1.2.826.0.1.3680043.8.498.75714899997203615784...,0,0,Sagittal

# Looking at class distributuion

In [14]:
Labels = [
    "ACL",
    "MCL",
    "Medial Meniscus",
    "Lateral Meniscus",
    "Medial OA",
    "Lateral OA",
    "PF OA",
    "Effusion",
    "Synovitis",
    "Baker's",
    "Contusion",
    "Fracture"
]

print(Train[TargetColumns].sum().sort_values(ascending=False))

Effusion            35.0
Synovitis           27.0
Medial Meniscus     26.0
ACL                 24.0
Lateral Meniscus    23.0
PF OA               21.0
Contusion           19.0
Fracture            18.0
Medial OA           15.0
Baker's             12.0
Lateral OA          11.0
MCL                  9.0
dtype: float64

# Basic Analysis

In [15]:
print("Train shape:", Train.shape)
print("Train Series shape:", TrainSeries.shape)

print("\nLabel distribution:")
print(Train[Labels].sum().sort_values())

print("\nSeries:")
print(TrainSeries.head())

print("\nAnatomical planes:")
print(TrainSeries["Anatomical_Plane"].value_counts())

print("\nFluid sensitive:")
print(TrainSeries["Fluid_Sensitive"].value_counts())

Train shape: (4407, 14)
Train Series shape: (24371, 5)

Label distribution:
MCL                  9.0
Lateral OA          11.0
Baker's             12.0
Medial OA           15.0
Fracture            18.0
Contusion           19.0
PF OA               21.0
Lateral Meniscus    23.0
ACL                 24.0
Medial Meniscus     26.0
Synovitis           27.0
Effusion            35.0
dtype: float64

Series:
                                    StudyInstanceUID  \
0  1.2.826.0.1.3680043.8.498.10004873229099053869...
1  1.2.826.0.1.3680043.8.498.10004873229099053869...
2  1.2.826.0.1.3680043.8.498.10004873229099053869...
3  1.2.826.0.1.3680043.8.498.10004873229099053869...
4  1.2.826.0.1.3680043.8.498.10004873229099053869...

                                   SeriesInstanceUID  Fluid_Sensitive  \
0  1.2.826.0.1.3680043.8.498.12343110195036213483...                1
1  1.2.826.0.1.3680043.8.498.13821229744997220641...                1
2  1.2.826.0.1.3680043.8.498.23084836536722595275...                0
3  1.2.826.0.1.3680043.8.498.40734206102458723096...                1
4  1.2.826.0.1.3680043.8.498.75714899997203615784...                0

   Fat_Suppression Anatomical_Plane
0                1         Sagittal
1                1            Axial
2                0          Coronal
3                1          Coronal
4                0         Sagittal

Anatomical planes:
Anatomical_Plane
Sagittal    9864
Coronal     8609
Axial       5898
Name: count, dtype: int64

Fluid sensitive:
Fluid_Sensitive
1    14010
0    10361
Name: count, dtype: int64

In [16]:
for Index in range(10):
    print("=" * 100)
    print(Train.iloc[Index]["Report"])

====================================================================================================
Técnica: RMN de la rodilla. Resultados: Rotura de menisco interno. Signo de necrosis avascular subcondral en el cóndilo femoral medial. Artrosis femorotibial medial. Derrame. . Impresión: Rotura de menisco interno. Signo de necrosis avascular subcondral en el cóndilo femoral medial. Artrosis femorotibial medial. Derrame.
====================================================================================================
[DATE]: * MR Knie Rechts 15ch AA Klinische Inlichtingen: [DATE]. Diagnostische vraagstellling: Meniscusscheur/mediaal? Scanprotocol (DRB) : sag intermediair gewogen seq zonder en met fs, ax/ cor pd gewogen seq fs, cor T1 gewogen seq Bevindingen:
====================================================================================================
Hallazgos:
No hay alteraciones en significativas de la médula ósea.
Ligamentos cruzados y colaterales dentro de límites normales.
Aumento de señal del cuerno posterior del menisco medial que no impresiona contactar con la
superficie articular, sin caracteres propios de rotura.
Menisco lateral de morfología y señal conservada, sin signos de rotura.
Úlceras condrales de espesor parcial con fenómenos condrales reparativos de la región central de
la zona de carga del cóndilo femoral medial. El resto de los cartílagos femorotibiales y de la tróclea
femoral sin alteraciones. Úlceras condrales espesor parcial de la rótula de distribución difusa.
No hay evidente derrame articular ni quistes poplíteos.
Engrosamiento y aumento de señal del tercio proximal del tendón rotuliano y de la inserción distal
del tendón cuadricipital con cambios entesopáticos.
Tendones de la pata de ganso, bíceps femoral y banda iliotibial dentro de límites normales.
Edema las partes blandas entre la banda iliotibial y el cóndilo femoral lateral sugiriendo fenómenos
de fricción.
Impresión:
Condropatía con lesiones grado 2 y 3 asociado a fenómenos condrales reparativos de la región
central de la zona de carga del cóndilo femoral medial.
Condropatía lesiones grado 2 de la rótula.
Tendinosis rotuliana proximal y cuadricipital distal con cambios entesopáticos.
Fenómenos de fricción de la banda iliotibial, correlacionar con clínica
====================================================================================================
 In the medial compartment, the meniscus is not torn and there is no focal chondrosis or chondral injury.
 The lateral compartment, there is suspicious incomplete discoid lateral meniscus without tear. There is no focal chondrosis or chondral injury.
 The patellofemoral joint, the patellar and trochlear cartilage appears congruent without chondral lesion. The medial patellofemoral ligament is intact.
 In the intercondylar notch, the anterior and posterior cruciate ligaments are intact. There is no tibial translation.
 The medial collateral ligament complexes are intact. The posteromedial oblique ligament is intact.
 The lateral collateral ligament complexes are intact. The popliteofibular ligament is intact. The meniscopopliteal fascicles are intact.
 The extensor mechanism is normal.
 No knee effusion is present. The surrounding musculature is normal. There is no fracture or bone contusion.  Suspicious incomplete discoid lateral meniscus without tear.
  Intact cartilage and ligaments of left knee.
====================================================================================================
CONSTATATIONS :

Fractures :
Aucune.

Alignement articulaire :
Normal.

Changements dégénératifs :
Chondropatie rétropatellaire modérée à sévère avec fissuration profonde impliquant les facettes médiale et latérale, au niveau de la facette médiale et œdème osseux réactionnel [grade 4].
Chondropatie légère des surfaces portantes des compartiments médial et latéral sans fissuration profonde.

Signal de la moelle osseuse :
Par ailleurs normal.

Ligament croisé antérieur : Normal.
Ligament croisé postérieur : Normal.
Ligament collatéral médial : Léger épaississement proximal compatible avec une ancienne entorse de bas grade.
Complexe du ligament collatéral latéral : normal.

Ménisque médial : Légers changements dégénératifs dégénérés sans signe de signe.
Ménisque latéral : Normal.

Tendons extenseurs : Normal.
Rétinacula patellaire : Normal.
Pes anserinus : Normal.

Coin postéro-latéral et postérieur : Normal.

Épanchement articulaire : Pas de liquide significatif.
Kyste de Baker : Aucun.

Autres trouvailles significatives :
Aucune.

CONCLUSION :
Chondropatie rétropatellaire modérée à sévère.
Entorse ancienne de bas grade du ligament collatéral médial.
Pas de déchirure méniscale.
====================================================================================================
Antecedentes Clínicos:
Condromalacia rotuliana.
Hallazgos:
No hay alteraciones difusas de señal de la médula ósea.
Ligamentos cruzados y colaterales de grosor y señal normales.
Menisco medial de morfología normal, con discreto edema de la unión meniscocapsular,
inespecífico.
Menisco lateral de morfología y señal normal, sin signos de rotura.
Cartílago de compartimentos femorotibiales y patelofemoral de grosor y señal normal.
No hay derrame articular. No hay quistes poplíteos.
Leve aumento de señal de fibras proximales del tendón patelar.
Tendones del cuádriceps, poplíteo, semimembranoso, bíceps femoral, banda iliotibial y tendones
de la pata de ganso de grosor y señal normales.
Edema del cojinete graso suprapatelar retrocuadricipital.
Discreto edema del tejido adiposo entre los tendones del sartorio, grácil y el cóndilo femoral
medial. También hay discreto edema del tejido adiposo entre el cóndilo femoral lateral y la banda
iliotibial.
Grupos musculares de trofismo y señal conservados.
Impresión:
Edema del cojinete graso suprapatelar retrocuadricipital, hallazgo inespecífico, podría representar
fenómenos de mal alineamiento patelar.
Leve tendinosis patelar proximal.
Signos que sugieren fenómenos de fricción posteromedial y de la banda iliotibial, correlacionar con
clínica
====================================================================================================
MRI of left knee with -Locator, SG PD FatSat, SG T2W FS, SG T1W, CO T2W FS, AX T2W FS

Findings:
> The contour of anterior cruciate ligament is in a straight line but increase signal intensity inside, likely due to sprain
> One cystic lesion posterior to ACL, maybe due to ganglion cyst
> The contour of posterior cruciate ligaments appearing within normal limit
> No definite tear of medial or lateral meniscus in this study
> Normal appearance of medial and lateral collateral ligaments
> No significant bone marrow edema or active cortical destruction in distal femur, proximal tibia and fibula in this study.
> Minimal joint effusion

Impression:
1. ACL sprain
2. Suspect ACL ganglion cyst

Suggest correlation with clinical manifestation.

====================================================================================================
МР находка: МР данни за ставен излив. Костите, формиращи дясната коляно са със непроменена структура. Малък костномозъчен едем локализиран в медиалния кондил на тибията.  Артикулиращият хрущял на фемура и тибията е изтънен от медиалната страна на ставата. Няма МР данни за руптура на предната кръстна връзка. Нормално представена задна кръстна връзка. Изобразява се увреда в задния рог на медиалния менискус – 2b степен. Нормално представен латерален менискус. Колатерални лигаменти със запазена цялост. Патела, хрущял на пателата, ретинакулуми – б.о. Заключение:  МР данни за парциална увреда на задния рог на медиалния менискус – степен 2b. Остеоартритни промени, по-изразени от медиалната страна на колянната става. Бекерова киста. Малък ставен излив.
====================================================================================================
SOL DİZ MRG. Tetkik protokolü: Çok düzlemli, çok sekanslı. Bulgular: Lateral menisküs ve medial menisküs normaldir. Ön çapraz bağ ve arka çapraz bağ, lateral ve medial kollateral ligaman normaldir.Distal kuadriseps ve patellar tendonlar normaldir. Patella normal yerleşimlidir. Retinaküler devamsızlık yoktur.Diz ekleminde minimal mayii artışı görüldü.Diz eklemini oluşturan kemik yapıların sinyal intensiteleri doğaldır.Sonuç: Diz ekleminde minimal mayii artışı dışından normal sınırlarda bulgular.
====================================================================================================
MRI of left Knee with
-Locator, SG PD FatSat, SG T1W, SG T2W FS, CO T2W FS, AX T2W FS


> Fracture of posterior tibial intercondylar eminence with avulsion fracture of PCL.
    Bone marrow edema in proximal tibia.
> The contour of PCL is not all in a straight line and increase signal intensity inside, in favor of partial tear.
> The contour of ACL appears to be within normal, no abnormal signal intensity is noted.
> Linear signal intensity in posterior horn of medial meniscus and anterior horn of lateral meniscus with extending into the surface, R/O tear.
> Both medial & lateral collateral ligaments appear to be within normal.
> Joint effusion and suprapatellar bursitis with suprapatellar and medial plicae; hypertrophy of the synovium, indicative of synovitis. Deep infrapatellar bursitis.
> Joint effusion and suprapatellar bursitis with suprapatellar and medial plicae; hypertrophy of the synovium with some fatty frondlike  excrescences ectending from the synovial surface over lateral suprapatellar region, in favor of  synovitis and R/O lipoma arborescens (diffuse synovial lipoma)
> Bone marrow edema over mdeial aspect of medial femoral condyle.
> Subcutaneous and muscle edema over left knee
> Wearing of articular cartilage and spur formation with subchondral edema

Impression:
1. Posterior tibial intercondylar eminence fracture with avulsion fracture of PCL and partial tear of PCL.
2. Bone contusion in medial femoral condyle and tibial plateau.
3. Osteoarthritis of left knee.
4. Degeneration of medial and lateral meniscus and R/O tear of anterior horn of lateral meniscus and posterior horn of medial meniscus.
5. Synovitis of left knee with suprapatellar and deep infrapatellar bursitis; R/O  lipoma arborescens over lateral aspect of  left knee.
6. Subcutaneous and muscle edema over left knee.
Suggest correlation with clinical manifestation

In [17]:
print(Train["Report"].isna().sum())
print(Train["Report"].str.len().describe())

0
count    4407.000000
mean     1097.905605
std       693.948925
min        52.000000
25%       587.500000
50%       977.000000
75%      1459.500000
max      4743.000000
Name: Report, dtype: float64

In [18]:
print(Train[["StudyInstanceUID", "Report"]].head())

                                    StudyInstanceUID  \
0  1.2.826.0.1.3680043.8.498.10004873229099053869...
1  1.2.826.0.1.3680043.8.498.10004945927472656027...
2  1.2.826.0.1.3680043.8.498.10009278692606631573...
3  1.2.826.0.1.3680043.8.498.10009639203170750274...
4  1.2.826.0.1.3680043.8.498.10013663742400736029...

                                              Report
0  Técnica: RMN de la rodilla. Resultados: Rotura...
1  [DATE]: * MR Knie Rechts 15ch AA Klinische Inl...
2  Hallazgos:\nNo hay alteraciones en significati...
3   In the medial compartment, the meniscus is no...
4  CONSTATATIONS :\n\nFractures :\nAucune.\n\nAli...

# To find the keywords

In [19]:
import re
import pandas as pd

FindingPatterns = {
    "ACL": [
        r"\bACL\b",
        r"anterior cruciate",
        r"ligament.*cruciate.*ant"
    ],
    
    "MCL": [
        r"\bMCL\b",
        r"medial collateral",
        r"ligament.*collateral.*med"
    ],
    
    "Medial Meniscus": [
        r"medial meniscus",
        r"meniscus med",
        r"menisco medial"
    ],
    
    "Lateral Meniscus": [
        r"lateral meniscus",
        r"meniscus lat",
        r"menisco lateral"
    ],
    
    "Medial OA": [
        r"medial.*osteo",
        r"medial.*arthro",
        r"medial compartment.*degenerative"
    ],
    
    "Lateral OA": [
        r"lateral.*osteo",
        r"lateral.*arthro",
        r"lateral compartment.*degenerative"
    ],
    
    "PF OA": [
        r"patellofemoral.*osteo",
        r"patellofemoral.*arthro",
        r"patellar.*osteoarthritis"
    ],
    
    "Effusion": [
        r"effusion",
        r"joint fluid",
        r"joint.*fluid",
        r"derrame",
        r"épanchement"
    ],
    
    "Synovitis": [
        r"synovitis",
        r"synovial.*hypertrophy"
    ],
    
    "Baker's": [
        r"baker",
        r"popliteal cyst",
        r"popliteal.*cyst"
    ],
    
    "Contusion": [
        r"bone contusion",
        r"bone bruise",
        r"bone marrow edema",
        r"contusion"
    ],
    
    "Fracture": [
        r"fracture",
        r"fracture.*bone",
        r"fraktur",
        r"fraktura"
    ]
}

for Label, Patterns in FindingPatterns.items():
    Pattern = "|".join(Patterns)
    
    Matches = Train["Report"].str.contains(
        Pattern,
        case=False,
        regex=True,
        na=False
    ).sum()
    
    print(f"{Label:20s}: {Matches:4d}")

ACL                 : 1578
MCL                 : 1596
Medial Meniscus     : 1496
Lateral Meniscus    : 1550
Medial OA           :  352
Lateral OA          :  345
PF OA               :  154
Effusion            : 2153
Synovitis           :  299
Baker's             : 1478
Contusion           :  889
Fracture            :  718